# Generated by Django 4.0 on 2022-01-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='smart_house.sensor'),
        ),
    ]