# Generated by Django 4.0 on 2022-01-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_house', '0002_alter_measurements_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('created_at', models.DateField()),
                ('sensors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='smart_house.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
    ]